name: pdrop
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py313h06a4308_0
  - python=3.13.2=hf623796_100_cp313
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py313h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py313h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - blinker==1.9.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.2
      - cycler==0.12.1
      - flask==3.1.0
      - fonttools==4.57.0
      - idna==3.10
      - imutils==0.5.4
      - itsdangerous==2.2.0
      - jax==0.6.0
      - jaxlib==0.6.0
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - ml-dtypes==0.5.1
      - multipledispatch==1.0.0
      - numpy==2.2.5
      - numpyro==0.18.0
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.2.1
      - pyparsing==3.2.3
      - pypylon==4.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.3
      - ruff==0.11.7
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - six==1.17.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - werkzeug==3.1.3
